name: datn_learn_flutter
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.2
  flutter_custom_clippers: ^0.1.1
  font_awesome_flutter: ^8.4.0
  firebase_auth: ^0.14.0+8
  shared_preferences: ^0.5.3+4
  bordered_text: ^0.1.4
  animated_floatactionbuttons: ^0.1.0
  url_launcher: ^5.0.2
  bottomreveal: ^1.0.0
  cached_network_image: ^1.1.1
  flutter_swiper: ^1.1.4
  wave: ^0.0.8
  calendar_views: ^0.5.2
  date_utils: ^0.1.0+2
  google_sign_in: 4.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/logoflutter.png
    - assets/codedemo.png
    - lib/ui/demo/widget/basics/button.dart
    - lib/ui/demo/widget/basics/appbar.dart
    - lib/ui/demo/widget/basics/checked_radio.dart
    - lib/ui/demo/widget/basics/container.dart
    - lib/ui/demo/widget/basics/icon.dart
    - lib/ui/demo/widget/basics/Image.dart
    - lib/ui/demo/widget/basics/scaffold.dart
    - lib/ui/demo/widget/basics/slider.dart
    - lib/ui/demo/widget/basics/text.dart
    - lib/ui/demo/widget/basics/text_field.dart
    - lib/ui/demo/widget/newapp/hello_flutter.dart

    - lib/ui/demo/widget/layout_contains_one_widget/align.dart
    - lib/ui/demo/widget/layout_contains_one_widget/aspectratio.dart

    - lib/ui/demo/widget/layout_contains_alot_widget/column.dart
    - lib/ui/demo/widget/layout_contains_alot_widget/row.dart
    - lib/ui/demo/widget/layout_contains_alot_widget/layout_builder.dart
    - lib/ui/demo/widget/layout_contains_alot_widget/stack.dart
    - lib/ui/demo/widget/layout_contains_alot_widget/listview.dart
    - lib/ui/demo/widget/layout_contains_alot_widget/listviewbiulder.dart
    - lib/ui/demo/widget/layout_contains_alot_widget/gridview.dart
    - lib/ui/demo/widget/layout_contains_alot_widget/table.dart


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
